package com.cstream.utils.logging;

import java.util.logging.Handler;
import java.util.logging.LogRecord;
import java.util.logging.Logger;

public class CLogHandler extends Handler {
	
	public static void setHandler(Logger logger) {
	
		Logger parent = logger.getParent();
		
		for (Handler handler: parent.getHandlers()) {
			parent.removeHandler(handler);
		}
		
		CLogHandler customHandler = new CLogHandler();
		customHandler.setFormatter(new LogFormatter());
		customHandler.setLevel(LogLevel.INFO);	
		
		// Change to DEBUG if you want to see more detailed error messages
		parent.setLevel(LogLevel.DEBUG);
		parent.addHandler(customHandler);
		
	}

	@Override
	public void publish(LogRecord r) {
		
		// Ignore FINE log messages - these are generated by JavaFX
		if (r.getLevel() == LogLevel.FINE) {
			return;
		}
		
		System.out.println(getFormatter().format(r));
		
	}

	@Override
	public void close() throws SecurityException {
		// Do nothing
	}

	@Override
	public void flush() {
		// Do nothing
	}
	
}
